FROM golang:1.15 as builder
WORKDIR /server
COPY ./main.go /server/
RUN CGO_ENABLED=0 go build

FROM python:3
RUN apt update
RUN apt install -y graphviz
RUN pip install diagrams
WORKDIR /diagrams
COPY listup_nodes.py /diagrams/
COPY --from=builder /server/server /diagrams/
ENTRYPOINT ["/diagrams/server"]
CMD [""]
