FROM golang:1.19 as builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build

FROM python:3
RUN apt update
RUN apt install -y graphviz
RUN pip install diagrams
WORKDIR /diagrams
COPY listup_nodes.py .
COPY --from=builder /src/sandbox .
ENTRYPOINT ["/diagrams/sandbox"]
CMD [""]
